---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-focal
    image: ubuntu:20.04
  - name: instance-noble
    image: ubuntu:24.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
