---
dependency:
  name: galaxy
  options:
    collections-path: .ansible/collections
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
